---
#tasks:
- name: Install apache
  ansible.builtin.apt:
    name: apache2
    state: absent
    update_cache: yes
- name: static app
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: "0644"
